# Generated by Django 3.2.21 on 2023-10-06 15:30

from django.db import migrations, models
import django.db.models.deletion
import nautobot.core.models.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dcim", "0001_initial"),
        ("tenancy", "0001_initial"),
        ("extras", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="virtualchassis",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AddField(
            model_name="rearporttemplate",
            name="device_type",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, related_name="rear_port_templates", to="dcim.devicetype"
            ),
        ),
        migrations.AddField(
            model_name="rearport",
            name="_cable_peer_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="rearport",
            name="cable",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="+", to="dcim.cable"
            ),
        ),
        migrations.AddField(
            model_name="rearport",
            name="device",
            field=nautobot.core.models.fields.ForeignKeyWithAutoRelatedName(
                on_delete=django.db.models.deletion.CASCADE, related_name="rear_ports", to="dcim.device"
            ),
        ),
        migrations.AddField(
            model_name="rearport",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AddField(
            model_name="rackreservation",
            name="rack",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="rack_reservations", to="dcim.rack"
            ),
        ),
        migrations.AddField(
            model_name="rackreservation",
            name="tags",
            field=nautobot.core.models.fields.TagsField(through="extras.TaggedItem", to="extras.Tag"),
        ),
        migrations.AddField(
            model_name="rackreservation",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="rack_reservations",
                to="tenancy.tenant",
            ),
        ),
    ]
